server {
    listen 80;

        resolver 1.1.1.1 168.95.1.1 valid=60s;
        resolver_timeout 3s;

        # 依專案調整
        server_name  marksix-qa-agent.good-start-168.com;
        server_name  marksix-qa-agent2.good-start-168.com;

        access_log /var/log/nginx/agent_access.log main;
        error_log /var/log/nginx/agent_error.log;

        location / {
                # 依專案調整
                # 前端_代理_agent-ng
                proxy_pass http://a6bb40c7060094a1c9e681cc82252cc4-91fee347e19e16bd.elb.ap-northeast-1.amazonaws.com;

                client_max_body_size 200M;
                proxy_buffer_size 8192k;
                proxy_buffers 4 8192k;
                proxy_redirect off;
                proxy_busy_buffers_size 16384k;
                proxy_temp_file_write_size 16384k;
                proxy_hide_header  Vary;
                proxy_ignore_headers Cache-Control Expires;

                proxy_ssl_server_name on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;

                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Connection "";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header proto-status $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_pass_header Set-Cookie;
                proxy_set_header   Accept-Encoding '';
                proxy_set_header   Referer $http_referer;
                #proxy_set_header Host $host;

                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 non_idempotent;
                proxy_ignore_headers Set-Cookie;

                include       mime.types;
                default_type  application/octet-stream;
        }

        location /api/ {
                # 後端_代理_springboot-agent
                proxy_pass http://ab34fd1f5c6344b81825a9238dce9031-f93a5e20ba856a1c.elb.ap-northeast-1.amazonaws.com:8081/;

                client_max_body_size 200M;
                proxy_buffer_size 8192k;
                proxy_buffers 4 8192k;
                proxy_redirect off;
                proxy_busy_buffers_size 16384k;
                proxy_temp_file_write_size 16384k;
                proxy_hide_header  Vary;
                proxy_ignore_headers Cache-Control Expires;

                proxy_ssl_server_name on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;

                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Connection "";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header proto-status $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_pass_header Set-Cookie;
                proxy_set_header   Accept-Encoding '';
                proxy_set_header   Referer $http_referer;

                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 non_idempotent;

                proxy_ignore_headers Set-Cookie;
        }
}