server {
    listen 80;

        resolver 1.1.1.1 168.95.1.1 valid=60s;
        resolver_timeout 3s;

        # 依專案調整
        server_name  marksix-qa-mpabm.good-start-168.com;
        


        access_log /var/log/nginx/mpabm_access.log main;
        error_log /var/log/nginx/mpabm_error.log;

        location / {                                
                # 依專案調整
                # 前端_會員_mpabm-ng
                proxy_pass http://a47eee8217cca46d394a3520dbf3d7a2-803af5b13fb15829.elb.ap-northeast-1.amazonaws.com;

                client_max_body_size 200M;
                proxy_buffer_size 8192k;
                proxy_buffers 4 8192k;
                proxy_redirect off;
                proxy_busy_buffers_size 16384k;
                proxy_temp_file_write_size 16384k;
                proxy_hide_header  Vary;
                proxy_ignore_headers Cache-Control Expires;

                proxy_ssl_server_name on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;

                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Connection "";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header proto-status $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_pass_header Set-Cookie;
                proxy_set_header   Accept-Encoding '';
                proxy_set_header   Referer $http_referer;
                #proxy_set_header Host $host;

                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 non_idempotent;
                proxy_ignore_headers Set-Cookie;

                include       mime.types;
                default_type  application/octet-stream;
        }

        location /api/ {
                # 後端_會員_springboot-portal
                proxy_pass http://aea0b916d57b244b39bf6f820c32c754-0ad712ffb5bcb25e.elb.ap-northeast-1.amazonaws.com:8082/;

                client_max_body_size 200M;
                proxy_buffer_size 8192k;
                proxy_buffers 4 8192k;
                proxy_redirect off;
                proxy_busy_buffers_size 16384k;
                proxy_temp_file_write_size 16384k;
                proxy_hide_header  Vary;
                proxy_ignore_headers Cache-Control Expires;

                proxy_ssl_server_name on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;

                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Connection "";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header proto-status $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_pass_header Set-Cookie;
                proxy_set_header   Accept-Encoding '';
                proxy_set_header   Referer $http_referer;

                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 non_idempotent;
                proxy_ignore_headers Set-Cookie;
        }
}