server {
    listen 80;

        resolver 8.8.8.8 1.1.1.1 168.95.1.1 valid=60s;
        resolver_timeout 3s;

        # 依專案調整
        server_name  79312a.htger65w.com  79369a.eve89clor.com 79612a.new99mobi.com;

        # 備用
        server_name  98568a.pknqsx8.com  89658a.okuhtf9.com  67568a.zscmkn6b.com; 

        access_log /var/log/nginx/agent_access.log main;
        error_log /var/log/nginx/agent_error.log;

        location / {                               
                # 依專案調整
                # 前端_代理_agent-ng
                proxy_pass http://a065439e5457643c0bed5458537e4c05-744f6766a6bcf6d4.elb.ap-northeast-1.amazonaws.com;
                proxy_buffer_size 8192k;
                proxy_buffers 4 8192k;
                proxy_redirect off;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_ignore_client_abort on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;
                proxy_set_header proto-status $scheme;
                proxy_set_header Host $host;

                include       mime.types;
                default_type  application/octet-stream;
        }

        location /api/ {
                # 後端_代理_springboot-agent
                proxy_pass http://a1f88bd0f758d4f67b38fbfcc63e2297-62dfffc317aa4133.elb.ap-northeast-1.amazonaws.com:8081/;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header REMOTE-HOST $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_ignore_client_abort on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;
                proxy_set_header proto-status $scheme;
        }

}
