server {
    listen 80 default;
	#listen 443 quic;
	#listen [::]:443 quic;
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;
	
	listen 443 quic reuseport;
	listen [::]:443 quic reuseport;
	
	ssl_certificate	/usr/local/nginx/conf/ssl/ca.pem;
	ssl_certificate_key /usr/local/nginx/conf/ssl/ca.key;
	
	ssl_early_data on;
	proxy_set_header Early-Data "$ssl_early_data";
	add_header alt-svc 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400';
	
	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; ";
	#proxy_set_header SNI-Host "www.microsoft.com";
	#proxy_ssl_name  www.microsoft.com;
	
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers HIGH:!aNULL:!MD5;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	
	ssl_session_cache shared:SSL:5m;
	
    server_name _;
    return 302 https://www.microsoft.com/;
    
    location ~ .*/(.svn)/.* {
        return 500;
    }
    
    location / {
        root   index.php;
        index  index.php index.html index.htm;
    }
    
    location ~* ^.+\.(jpg|jpeg|gif|css|png|js|ico|html)$ {
        access_log        off;
        expires           24h;
    }
    
    error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        root   html;
    }
}