server {
    listen 80;
    server_name  hz1ap.6-aa.com hz2ap.6-bb.com hz3ap.6-cc.com hz4ap.6-ee.com hz5ap.6-ff.com;
    server_name  hz1ap.6-a7.com hz2ap.6-b1.com hz3ap.6-c1.com hz4ap.6-e1.com hz5ap.6-f1.com;
    server_name  aws-tw-chk.6-aa.com hk-chk.6-bb.com;

    index index.html;
    access_log /var/log/nginx/web_access.log main buffer=192k flush=30s;
    error_log /var/log/nginx/web_error.log;

    ## Mobile Detection
    if ($http_user_agent ~* "(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino") {
        set $mobile_request 'ok';
    }


    ## Root Location
    location / {

        add_header Device 'PC';
        root /data/agent/;

        #APP、H5
        if ($mobile_request = 'ok') {
            add_header Device 'Mobile';
            root  /data/agphone/;
        }

        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.html?s=$1 last;
            break;
        }

        try_files $uri /$uri /index.html;
    }
    location /api/ {
        # 後端_代理_springboot-agent
        proxy_pass http://agent-6-live:8081/;
        client_max_body_size 200M;
    }
}  ## END...

