server {
    listen 80 default;
    server_name _;
    rewrite ^/(.*)$ https://www.google.com/$1 permanent;
    
    location ~ .*/(.svn)/.* {
        return 500;
    }
    
    location / {
        root   index.php;
        index  index.php index.html index.htm;
    }
    
    location ~* ^.+\.(jpg|jpeg|gif|css|png|js|ico|html)$ {
        access_log        off;
        expires           24h;
    }
    
    error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        root   html;
    }
}
