server {
    listen 6002;

    server_name _;
    root  /data/openCenter/;
    index index.html;
    access_log /var/log/nginx/web_access.log main buffer=192k flush=30s;
    error_log /var/log/nginx/web_error.log;

    add_header Device 'Mobile';

    ## Mobile's Root Location
    location / {
        try_files $uri /$uri /index.html;
    }
    location /api/ {
        # 後端_自開彩_springboot-selfopenControl
        proxy_pass http://springboot-selfopencontrol:8099/;
        client_max_body_size 200M;
    }
}  ## END...