server {
    listen 80;

        resolver 8.8.8.8 1.1.1.1 168.95.1.1 valid=300s;
        resolver_timeout 3s;

        # 依專案調整
        server_name    opencenter.kxkvv.com;


        access_log /var/log/nginx/opencenter_access.log main;
        error_log /var/log/nginx/opencenter_error.log;

        location / {

            # 依專案調整
            # 前端_對外開發_opencenter-ng
            proxy_pass http://aa3c2d3f225d044c38c0e0d5e6193cdf-787cea4426f2928d.elb.ap-northeast-1.amazonaws.com;
            proxy_buffer_size 8192k;
            proxy_buffers 4 8192k;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_ignore_client_abort on;
            proxy_connect_timeout 60;
            proxy_read_timeout 60;
            proxy_send_timeout 60;
            proxy_set_header proto-status $scheme;
            proxy_set_header Host $host;

            include       mime.types;
            default_type  application/octet-stream;
        }
        location /api/ {
            # 獨立環境_後端_開獎中心(selfopen)_springboot-selfopen
            proxy_pass http://a8092f740d5f444789087c2fcf7668fb-f10b1d57d470356b.elb.ap-northeast-1.amazonaws.com/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_ssl_server_name on;

            proxy_ignore_client_abort on;
            proxy_connect_timeout 60;
            proxy_read_timeout 60;
            proxy_send_timeout 60;
            proxy_set_header proto-status $scheme;
        }
}
