server {
    listen 80;

        resolver 8.8.8.8 1.1.1.1 168.95.1.1 valid=60s;
        resolver_timeout 3s;

        # 依專案調整
        server_name  everycolor-search.good-start-168.com;

        access_log /var/log/nginx/search_access.log main;
        error_log /var/log/nginx/search_error.log;

        location / {
                # 依專案調整
                # 前端_查詢_search-ng
                proxy_pass http://a9776253180ff4c4a974903c6d0850ef-a8ac3ee2adcf7708.elb.ap-northeast-1.amazonaws.com;
                proxy_buffer_size 8192k;
                proxy_buffers 4 8192k;
                proxy_redirect off;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_ignore_client_abort on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;
                proxy_set_header proto-status $scheme;
                #proxy_set_header Host $host;

                include       mime.types;
                default_type  application/octet-stream;
        }

        location /api/ {
                #後端_導航_springboot-searchplatform
                proxy_pass http://a173dfd004a9a49e7a0978c918c99f87-4b826f2f08c05258.elb.ap-northeast-1.amazonaws.com:8089/;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header REMOTE-HOST $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_ignore_client_abort on;
                proxy_connect_timeout 60;
                proxy_read_timeout 60;
                proxy_send_timeout 60;
                proxy_set_header proto-status $scheme;
        }

}
