server {
    listen 80;
    server_name  tt1mp.10-c.com tt2mp.10-d.com tt3mp.10-f.com tt4mp.10-h.com tt5mp.10-i.com tt1mp.10-m.com tt2mp.10-n.com tt3mp.10-p.com tt4mp.10-q.com tt5mp.10-u.com;
    server_name  tt2mp.10-c.com tt3mp.10-c.com tt4mp.10-f.com tt5mp.10-f.com;
    server_name  1mp.369-10a.com 2mp.369-10b.com 3mp.369-10c.com 4mp.369-10d.com 5mp.369-10f.com 1mp.369-10u.com 2mp.369-10y.com 3mp.369-10i.com 4mp.369-10o.com 5mp.369-10p.com;
    index index.html;
    access_log /var/log/nginx/web_access.log main buffer=192k flush=30s;
    error_log /var/log/nginx/web_error.log;

    ## Mobile Detection
    if ($http_user_agent ~* "(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino") {
        set $mobile_request 'ok';
    }


    ## Root Location
    location / {

        add_header Device 'PC';
        root /data/menber/;

        #APP、H5
        if ($mobile_request = 'ok') {
            add_header Device 'Mobile';
            root  /data/mphone/;
        }

        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.html?s=$1 last;
            break;
        }

        try_files $uri /$uri /index.html;
    }
    location /api/ {
        #後端_會員_springboot-portal
        proxy_pass http://portal-10-live:8082/;
        client_max_body_size 200M;
    }
}  ## END...
