server {
    listen 80;
    server_name ttkx-openmark.flourish-986.com;

    root /data/openmark/;
    index index.html;
    access_log /var/log/nginx/web_access.log main buffer=192k flush=30s;
    error_log /var/log/nginx/web_error.log;

    ## Mobile Detection
    if ($http_user_agent ~* "(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino") {
        set $mobile_request 'ok';
    }

    ## Root Location
    location / {

        #add_header Cache-Control 'no-cache';

        #PC
        proxy_pass http://127.0.0.1:6001;
        # return 502;   #For Debug

        #APP、H5
        if ($mobile_request = 'ok') {
            proxy_pass http://127.0.0.1:6002;
            # return 503;   #For Debug
        }
    }
}  ## END...
