server {
    listen 80;
    #hxtronht_後台
    server_name  hxtronht-ad.333-api.net ;

    index index.html;
    access_log /var/log/nginx/web_access.log main buffer=192k flush=30s;
    error_log /var/log/nginx/web_error.log;

    ## Mobile Detection
    if ($http_user_agent ~* "(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino") {
        set $mobile_request 'ok';
    }


    ## Root Location
    location / {

        add_header Device 'PC';
        root /data/hxtronht/;

        #APP、H5
        #if ($mobile_request = 'ok') {
        #    add_header Device 'Mobile';
        #    root  /data/hxtronht/;
        #}

        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.html?s=$1 last;
            break;
        }

        try_files $uri /$uri /index.html;
    }
    location /api/ {
        #後端_開獎_springboot-selfopenzx-tron
        proxy_pass http://selfopenzx-tron:8280/;
        client_max_body_size 200M;
    }
}  ## END...
